---
- name: Ensure data and appdata folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ docker_user }}"
    group: docker
    mode: '0755'
  with_items:
    - "{{ docker_data_path }}"
    - "{{ docker_appdata_path }}"
