---
dependencies: []

galaxy_info:
  role_name: post_install
  author: xerifeazeitona
  description: Fedora Server post install configuration
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - 33
        - 34
        - 35
