---
dependencies: []

galaxy_info:
  role_name: docker
  author: xerifeazeitona
  description: Docker for Fedora
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - all
